version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfullyyyyy
artifacts:
  files:
    - target/pm-ui.jar
  discard-paths: yes